### ISSUE TITLE
@Consistency annotation results in Kotlin compilation error [DATACASS-797]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#964]
**[Gautam Jolly](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50235)** opened **[DATACASS-797](https://jira.spring.io/browse/DATACASS-797?redirect=false)** and commented

Compilation of a Kotlin function, that is annotated with `@Consistency`, results in compilation error "**_An annotation argument must be a compile-time constant_**". Note that fhis feature worked well in spring-data-cassandra-2.1.X.

```java
@Consistency(DefaultConsistencyLevel.QUORUM)
fun doSomething()
```

The equivalent Java code works just fine:

```java
@Consistency(DefaultConsistencyLevel.QUORUM)
public void doSomething();
```

---

**Affects:** 3.0.3 (Neumann SR3)

**Attachments:**
- [demo-java-kotlin.zip](https://jira.spring.io/secure/attachment/28194/demo-java-kotlin.zip) (_22.86 kB_)
